[package]
name = "pixel"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
console = "0.16.1"
eframe = "0.32.2"
egui_extras = "0.32.2"
env_logger = "0.11.8"
image = "0.25.8"
photon-rs = "0.3.3"
rand = "0.9.2"
